name: Docker Build
env:
  SERVICE: 'payments'

on:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Build Docker image
        run: docker build -t tamerlanchik/solar_${SERVICE}_${GITHUB_REF##*/}:${GITHUB_SHA}  -t tamerlanchik/solar_${SERVICE}_${GITHUB_REF##*/}:latest .
      - name: Push the image
        run: docker push tamerlanchik/solar_${SERVICE}_${GITHUB_REF##*/}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: pull docker image
        uses: appleboy/ssh-action@master
        env:
          DB_ROOT: ${{ secrets.DB_CONNECT_ROOT }}
          CLIENT_ID: ${{ secrets.MONEY_CLIENT_ID }}
          JWT_PAYMENT_TOKEN_SECRET: ${{ secrets.JWT_PAYMENT_SECRET }}
        with:
          envs: GITHUB_SHA, GITHUB_REF, SERVICE, DB_ROOT, CLIENT_ID, JWT_PAYMENT_TOKEN_SECRET
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: sudo 
            FACTER_image_tag=${GITHUB_SHA} FACTER_db_root=${DB_ROOT} FACTER_client_id=${CLIENT_ID} FACTER_jwt_payment_secret=${JWT_PAYMENT_TOKEN_SECRET}
            /opt/puppetlabs/bin/puppet apply -t --tags gobackend::${SERVICE}::${GITHUB_REF##*/} 
            /etc/puppetlabs/code/environments/production/manifests/site.pp; [[ "02" == *"${PIPESTATUS[0]}"* ]]
       
